### ISSUE TITLE
Preview not working - Uncaught TypeError: Cannot read properties of undefined (reading 'fetch')

### ISSUE THREAD

**Issue by jmertic** [prose/prose#1131]
```
Uncaught TypeError: Cannot read properties of undefined (reading 'fetch')
    at n.e (prose.js:3:9345)
    at t (prose.js:38:5579)
    at Object.defer (prose.js:38:5867)
    at n.preview (prose.js:3:10584)
    at n.render (prose.js:3:7021)
    at n.<anonymous> (prose.js:3:702)
    at d (prose.js:33:1924)
    at Object.fireWith (prose.js:33:2704)
    at i (prose.js:35:509)
    at XMLHttpRequest.i (prose.js:35:5946)
```

Config at https://github.com/Chippewa-Levy-Committee/blog/blob/main/_config.yml

**Comment by babbitt** [comment]
Closing as I can't re-produce. Feel free to open with new/more detail if you have issues.
